services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WD_LANG: ${WD_LANG:-en}
      FALLBACK_LANG: ${FALLBACK_LANG:-en}
      WIKIBASE_HOST: ${WIKIBASE_HOST:-wikibase}
      WIKIBASE_PORT: ${WIKIBASE_PORT:-80}
      TEXTIFIER_DB_HOST: ${TEXTIFIER_DB_HOST:-db}
      TEXTIFIER_DB_PORT: ${TEXTIFIER_DB_PORT:-3306}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME_LABEL:-label}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SAVE_LABELS: ${SAVE_LABELS:-false}
      SAVE_WD_TO_HF: ${SAVE_WD_TO_HF:-false}
      SAVE_TO_VECTORDB: ${SAVE_TO_VECTORDB:-false}
      SAVE_VECTORS_TO_HF: ${SAVE_VECTORS_TO_HF:-false}
      FORCE_DOWNLOAD_DUMP: ${FORCE_DOWNLOAD_DUMP:-false}
      DUMP_PATH: ${DUMP_PATH:-data/wd_dump.gz}
      READER_QUEUE_SIZE: ${READER_QUEUE_SIZE:-128}
      READER_BATCH_SIZE: ${READER_BATCH_SIZE:-16}
      HF_CHUNK_SIZE: ${HF_CHUNK_SIZE:-10000}
      JINA_API_PATH: /workspace/API_tokens/jina_api.json
      ASTRA_API_PATH: /workspace/API_tokens/datastax_api.json
      WD_HF_API_PATH: /workspace/API_tokens/wd_hf_api.json
      VECTORS_HF_API_PATH: /workspace/API_tokens/vectors_hf_api.json
    volumes:
      - ./data:/workspace/data
      - ./API_tokens:/workspace/API_tokens:ro
      - ./WikidataTextifier:/opt/WikidataTextifier:ro
    restart: "no"
    networks:
      - wdtextifier

networks:
  wdtextifier:
    external: true
    name: ${WDTEXTIFIER_COMPOSE_NETWORK:-wikidatatextifier_default}
